Add armhf toolchain

diff --git a/toolchain/kindle-sdk-nomount.patch b/toolchain/kindle-sdk-nomount.patch
--- a/toolchain/kindle-sdk-nomount.patch
+++ b/toolchain/kindle-sdk-nomount.patch
@@ -1,25 +1,42 @@
 diff --git a/gen-sdk.sh b/gen-sdk.sh
-old mode 100644
-new mode 100755
-index 81000d7..3edd872
+index 96f14ad..44d89f4 100644
 --- a/gen-sdk.sh
 +++ b/gen-sdk.sh
-@@ -75,7 +75,8 @@ Setup_SDK() {
+@@ -1,6 +1,6 @@
+ #!/bin/sh
+ 
+-set -e # Stop on error
++set -xe # Stop on error
+ 
+ RM_If_Exists() {
+     if [ -d $1 ] || [ -f $1 ]; then
+@@ -17,7 +17,7 @@ Setup_SDK() {
+ 
+     # Just in case
+     set +e
+-    sudo umount "./cache/${tc_target}/firmware/mnt"
++    # sudo umount "./cache/${tc_target}/firmware/mnt"
+     set -e
+     
+     case $sdk_target in
+@@ -89,7 +89,10 @@ Setup_SDK() {
      cd "./cache/${tc_target}/firmware/"
          gunzip rootfs.img.gz
          mkdir mnt
 -        sudo mount -o loop rootfs.img mnt
 +        # sudo mount -o loop rootfs.img mnt
++        set +e # will error because it can't create two symlinks
 +        7zz x rootfs.img -omnt/ -snld
++        set -e
      cd ../../..
-
+ 
      echo "[*] Wiping target pkgconfig files"
-@@ -165,7 +166,7 @@ Setup_SDK() {
-
+@@ -183,7 +186,7 @@ Setup_SDK() {
+ 
      echo "[*] Cleaning up"
      cd "./cache/${tc_target}/firmware/"
 -        sudo umount mnt
 +        # sudo umount mnt
      cd ../../..
-
+ 
      echo "===================================================================================================="
